# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b0baa223a14670a55636c3ea9c8acab30c14137f28d83d5594a76657359cc15d09b1f7105f69dc9bf04b021fa801a25c7df768a34d574602a8738634c125fa3

test:
  secret_key_base: 3deb60312de6618a3f8235915b89a4a93636df3ce123e9906a19257b5af9d1964a1d14ad2ce46cc9f1b2fff8a5f1bf1b437b7dab7bdeacd25a6d3937886a9b55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
